### ISSUE TITLE
New logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [jordanpotti/CloudScraper#1]
Hello! I want to contribute on your project with making logo design. What do you think about it?

Best Regards,
Arslan Şahin
Graphics Designer

**Comment by jordanpotti** [comment]
Absolutely! Every good open source tool has a logo :) pull requests are always welcome!

**Comment by jordanpotti** [comment]
Hey very cool! I do like it and will update the tool with it when I get a chance! Thank you very much!  Awesome work 👍
